apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-postgres-config
data:
  POSTGRES_HOST: task-manager-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: task_manager
  DB_DRIVER_CLASS_NAME: org.postgresql.Driver
  DB_URL: jdbc:postgresql://postgres:5432/task_manager
