apiVersion: v1
kind: Secret
metadata:
  name: task-manager-postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: aGFtYWRhY2gyMDAz
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: aGFtYWRhY2gyMDAz
